name: emotion-driven-markets
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - tensorflow
  - pytorch
  - transformers
  - yfinance
  - tqdm
  - matplotlib
  - seaborn
  - joblib
  - pytest
  - pip
